### ISSUE TITLE
負荷可視化のためのアレコレ

### ISSUE THREAD

**Issue by karupanerura** [karupanerura/isucon2014-elimination#3]
さくっと使えるように用意しておく
- [x] Apacheのcombined logにruntimeを出すためのCustomLog (最初の計測であったほうがよい)
- [x] pt-query-digest
- [x] dstat
- [x] mackerel-agent
- [x] DBIx::QueryLog
- [x] Devel::KYTProf

**Comment by karupanerura** [comment]
@masasuzu おねがいします！

**Comment by karupanerura** [comment]
mackerel-agent: https://mackerel.io/orgs/isucon2014-elimination-kura-team/instruction-agent

**Comment by karupanerura** [comment]
> DBIx::QueryLog
> Devel::KYTProf

cpanfileに書いてcarton install

**Comment by karupanerura** [comment]
dstat: yum install dstat

**Comment by karupanerura** [comment]
percona-toolkit: http://www.percona.com/doc/percona-server/5.5/installation/yum_repo.html

**Comment by karupanerura** [comment]
Apache: %T %Dって書く

**Comment by masasuzu** [comment]
tcpdump経由のpt-query-digest

```
yum install tcpdump

sudo /usr/sbin/tcpdump -i eth0 port 3306 -s 65535 -w /tmp/mysql.pcap &;
sleep 60;
sudo pkill tcpdump ;
sudo /usr/sbin/tcpdump -s 65535 -x -nn -q -tttt -l -r /tmp/mysql.pcap | pt-query-digest --type tcpdump --explain "h=localhost,u=root" --limit=50 > /tmp/digest.txt;
```

slow queryに全SQL吐かせてそれを食わせる方がやはり良い
