### ISSUE TITLE
当日のコミュニケーション手段を用意する

### ISSUE THREAD

**Issue by kfly8** [karupanerura/isucon2014-elimination#5]
候補
# お話系
- 口頭
- IRC
- facebook messanger
- mail
- --gitter-- 有料とのことなので、一旦おく
- slack
# ドキュメントの共有
- Google Drive
- gists private
- nopaste 立てる

**Comment by karupanerura** [comment]
Gitterは有料プラン使わないとダメそう。

**Comment by karupanerura** [comment]
あと、口頭でガンガン話す。

**Comment by kfly8** [comment]
@karupanerura ++

**Comment by kfly8** [comment]
- ホワイトボードはあった方がいいかな？
- コンソールは画面共有した方がいいかな？

**Comment by kfly8** [comment]
#まとめ
- **かなり困ったり、迷ったりしたら、口頭**
- **slackを見れば、全ての変更を追えるようにする**
- 開発方針、TODOはgithub issueを用意する( slack の通知設定済み )
- 調査メモは、google drive または slack のpost または gist。ただし、どれにしても調査開始前に、slackにリンクを張って共有すること。 
- ホワイトボードは予選時は、社内に転がっているのを使う
- コンソールの画面共有は、`cd ..` とか見ても余り意味ないので、却下。予選には間に合わないけど、ChatOpsになるように倒して行ければよいと思っている。

**Comment by kfly8** [comment]
良さそうであれば、closeしてほしく！@karupanerura

**Comment by masasuzu** [comment]
OKそうです。ありがとうございます。
