### ISSUE TITLE
予選タイムスケジュール

### ISSUE THREAD

**Issue by kfly8** [karupanerura/isucon2014-elimination#6]
パッと思いつくマイルストーンをおいてみた。
他にマイルストーンに抜けがないか確認頂きたく。

9/27
- 9:00 集合
- 10:00 競技開始
- 12:00 昼飯
- 17:30 レギュレーションに沿った手順でベンチマークを取る
- 18:00 競技終了
- 19:00 飲む

**Comment by masasuzu** [comment]
> 09/24 13:54 ^masashi : 当日 夕方に日本酒を呑まないといけない前々からの用事があるので、"19:00 飲む" 参加できないです

**Comment by kfly8** [comment]
以下、ドキュメントにて、共有しあう。
変更点があれば適宜修正する

https://docs.google.com/document/d/1bndDHWuhQjsYFH7L2-PtZJrIdimFHRC39lb38mTM62c/edit?usp=sharing
